### ISSUE TITLE
Get final state

### ISSUE THREAD

**Issue by zvitek** [inakianduaga/redux-state-history#15]
Hello, redux-state-history works well but I have one question.
It's possible to get only current state without history? 

I have prepared the order process and I would like to save user's final state into database.

Thank you

**Comment by inakianduaga** [comment]
> It's possible to get only current state without history?

I don't think I understand, you mean when you click on the download button on the debug tool? Otherwise you wouldn't need this package just for that since any on any redux application you have access to the full current state?

**Comment by zvitek** [comment]
Yes, I can download it through redux. 
I didn't want to create two functionalities because I will save history also.
I thought it might be good. Does not matter. :)

Thx for rection
